//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int IdArticle { get; set; }
        public System.DateTime DATE { get; set; }
        public string Descriptif { get; set; }
        public Nullable<int> IdImage { get; set; }
        public int IdAcces { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Image Image { get; set; }
    }
}
