//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cv
    {
        public int IdCv { get; set; }
        public string NomCv { get; set; }
        public string Url { get; set; }
        public System.DateTime Date { get; set; }
        public int IdCompetence { get; set; }
        public int IdProfile { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
