//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscrit
    {
        public int IdInscrit { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Siret { get; set; }
        public Nullable<int> IdAcces { get; set; }
        public int IdAdresse { get; set; }
        public int IdMaintenance { get; set; }
        public int IdCandidature { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Adresse Adresse { get; set; }
        public virtual Candidature Candidature { get; set; }
        public virtual Maintenance Maintenance { get; set; }
    }
}
