//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baeEntities : DbContext
    {
        public baeEntities()
            : base("name=baeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acces> Acces { get; set; }
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Anciennete> Anciennete { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Candidature> Candidature { get; set; }
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Cv> Cv { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Inscrit> Inscrit { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<Metier> Metier { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Offre> Offre { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Remuneration> Remuneration { get; set; }
    }
}
