//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Candidature = new HashSet<Candidature>();
        }
    
        public int IdOffre { get; set; }
        public string NumeroOffre { get; set; }
        public System.DateTime Date { get; set; }
        public string TitreOffre { get; set; }
        public string DescriptionOffre { get; set; }
        public int IdRegion { get; set; }
        public int IdMetier { get; set; }
        public int IdRemuneration { get; set; }
        public int IdAnciennete { get; set; }
        public int IdContrat { get; set; }
    
        public virtual Anciennete Anciennete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidature> Candidature { get; set; }
        public virtual Contrat Contrat { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual Region Region { get; set; }
        public virtual Remuneration Remuneration { get; set; }
    }
}
